config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :transactions, controller: "transactions", only: [:new, :create]

  resources :users do
  	resources :orders, controller: "orders", only: [:new, :create]
  end

  resources :orders, controller: "orders", only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: "logout"
  get "/signup" => "users#new", as: "signup"
  get 'braintree/new'
  post 'braintree/checkout' => "braintree#checkout", as: "braintree_checkout"
  post 'verify_user' => "users#verify", as: "verify_user"
  post 'unverify_user' => "users#unverify", as: "unverify_user"

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
	def new
		@user = current_user
		@currency = params[:currency]
  		@client_token = Braintree::ClientToken.generate
  	end

  	def checkout
  		@currency = params[:deposit][:currency]
  		@amount = params[:deposit][:amount]
		nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

		result = Braintree::Transaction.sale(
			:amount => @amount, #this is currently hardcoded
			:payment_method_nonce => nonce_from_the_client,
			:options => {
			:submit_for_settlement => true
			}
		)

		if result.success?
			@user = current_user
			@deposit = @user.deposits.new(deposit_params)
			if @deposit.save
				@balance = @user.balances.find_by(currency: @currency)
				new_balance = @balance.amount + @amount.to_f
				@balance.update(amount: new_balance)
				redirect_to user_path(current_user), :flash => { :success => "Succesfully deposited #{@amount} #{@currency}" }
			else
				redirect_to root_path, :flash => { :error => "Critical error, contact admin" }
			end
		else
			redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
		end
	end

	private
	def deposit_params
		params.require(:deposit).permit(:currency, :amount)
	end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<h1>Add <%= @currency %> to <%= @user.username %>'s account</h1>



<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

  <input name="deposit[currency]" type="hidden" value="<%= @currency %>">
  <div>
    <label for="amount"><%= @currency %></label>
    <input id="amount" name="deposit[amount]" type="number" step="0.01" placeholder="100.00">
  </div>
  



    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Add funds", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>