config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :transactions, controller: "transactions", only: [:new, :create]

  resources :users do
  	resources :orders, controller: "orders", only: [:new, :create]
  end

  resources :orders, controller: "orders", only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: "logout"
  get "/signup" => "users#new", as: "signup"
  get 'braintree/new'
  post 'braintree/checkout' => "braintree#checkout", as: "braintree_checkout"
  post 'verify_user' => "users#verify", as: "verify_user"
  post 'unverify_user' => "users#unverify", as: "unverify_user"

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :orders, dependent: :destroy
	has_many :balances, dependent: :destroy
	has_many :deposits, dependent: :destroy
	enum role: [:user, :admin]

	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:verify, :unverify]

	before_action :require_owner, only: [:edit, :update]

	def index
		@users = User.all.order(:id)
	end

	def new
		if current_user == nil || current_user.admin?
			@user = User.new
		else
			redirect_to root_path
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			starting_balance(@user)
			redirect_to login_path, :flash => { :success => "User successfully created" }
		else
			redirect_to new_user_path, :flash => { :error => "Failed to create users" }
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

    	if @user.update(user_params)
    		redirect_to user_path(@user.id), :flash => { :success => "User successfully updated" }
    	else	
			render 'edit', :flash => { :error => "Failed to update user" }
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path, :flash => { :success => "User successfully destroyed" }
		else
			redirect_to user_path(@user.id), :flash => { :success => "Failed to delete user" }
		end
	end

	def show
		@user = User.find(params[:id])
		@balances = @user.balances
		@orders = @user.orders
	end

	def verify
		@user = User.find(params[:id])
		@user.verified = true
		@user.save
	end

	def unverify
		@user = User.find(params[:id])
		@user.verified = false
		@user.save
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def require_owner
		unless current_user == User.find(params[:id]) || current_user.admin?
			redirect_to users_path, :flash => { :error => "You do not have permission to view this page" }	
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_balance.html.erb
<div class="container text-light bg-dark py-2 my-2">
	
	<h3>Your Balance</h3>
		<% @balances.each do |b| %>
		<div class="row px-3">
			<div class="col-6 text-left"><%= b.currency %>: <%= b.amount %>
			</div>	
			<div class="col-6 text-right">
				<%= link_to "Add Currency", braintree_new_path(currency: b.currency) %>
			</div>
		</div>
		<% end %>
</div>

app/views/users/_form.html.erb
<div class="form-group">
	<%= form.label :username %>
	<%= form.text_field :username, class: "form-control" %>
</div>

<div class="form-group">
	<%= form.label :email %>
	<%= form.text_field :email, class: "form-control" %>
</div>

<div class="form-group">
	<%= form.label :password %>
	<%= form.text_field :password, class: "form-control" %>
</div>

<div class="form-group">
	<%= form.label :password_confirmation %>
	<%= form.text_field :password_confirmation, class: "form-control" %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit user</h1>

	<div class="row">
		<div class="col-md-6">
			<%= form_for @user, method: :patch, controller: "users#update" do |f| %>
				<%= render partial: '/users/form', object: f %>
				<%= f.submit "Edit User", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div><h1>All Users</h1></div>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Username</th>
				<th scope="col">Email</th>
				<th scope="col">Verified</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each_with_index do |u,i| %>
			<tr>
				<th scope="row"><%= "#{i+1}." %></th>
				<td><%= link_to "#{u.username.capitalize}", user_path(u.id) %></td>
				<td><%= u.email %></td>
				<% if current_user != nil %>
					<% if current_user.admin? %>
					<td class="verified">
					<% else %>
					<td>
					<% end %>
				<% else %>
					<td>
				<% end %>
					<% if u.verified? %>
					<input type="hidden" value="<%=u.id%>">
					<span class="fa fa-check" aria-hidden="true"></span>
					<% else %>
					<input type="hidden" value="<%=u.id%>">
					<span class="fa fa-times" aria-hidden="true"></span>
					<% end %>		
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	$(".verified").on("click", function(){
		var iSelector = $(this).find("span")
		var hiddenUser = $(this).find("input")
		
		if (iSelector.hasClass('fa-times')) {
			iSelector.removeClass('fa-times')
			iSelector.addClass('fa-check')
			$.ajax({
				method: "POST",
				url: "/verify_user",
				data: { id: hiddenUser.val() }
			});
		} else {
			iSelector.removeClass('fa-check')
			iSelector.addClass('fa-times')
			$.ajax({
				method: "POST",
				url: "/unverify_user",
				data: { id: hiddenUser.val() }
			});
		}
	});
</script>

app/views/users/new.html.erb
<div class="container">
	<h1>Sign up</h1>

	<div class="row">
		<div class="col-md-6">
			<%= form_for @user do |f| %>
				<%= render partial: '/users/form', object: f %>
				<%= f.submit "New User", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid bg-light">

<div class="container text-light bg-dark">
	<h1><%= @user.username %>'s profile</h1>
</div>
<div class="container">
	<div class="row">
		<div class="col-6">Email: <%= @user.email%></div>
		<div class="col-6">Member since: <%= @user.created_at.to_date %></div>

	</div>
</div>

<% if current_user == @user %>

<div class="container text-light bg-dark">
	<% if current_user != nil %>
<h2>Welcome <%= current_user.username.capitalize %></h2>
	<% end %>
</div>

<%= render partial: "balance" %>

<div class="container text-light bg-dark">
	<h2><%= link_to "New Order", new_user_order_path(user_id: @user.id) %></h2>
</div>


<% end %>


<div class="container text-light bg-dark">
	<h2>Buy orders</h2>
</div>

<div class="container">
	<% @orders.each do |order| %>
	<div>
		<%= "#{order.user.username} is buying #{order.buy_amount} #{order.buy_currency} for #{order.sell_amount} #{order.sell_currency}" %>
		<%= link_to "SELL #{order.buy_currency}", { :controller => "transactions", :action => "new", :id => order.id } %>
	</div>
	<% end %>
</div>

<div class="container text-light bg-dark">
	<h2>Sell orders</h2>
</div>

<div class="container">
	<% @orders.each do |order| %>
	<div>
		<%= "#{order.user.username} is selling #{order.sell_amount} #{order.sell_currency} for #{order.buy_amount} #{order.buy_currency}" %> 
		<%= link_to "BUY #{order.sell_currency}", { :controller => "transactions", :action => "new", :id => order.id } %>
  	</div>
  	<% end %>
</div>
	
</div>