config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :transactions, controller: "transactions", only: [:new, :create]

  resources :users do
  	resources :orders, controller: "orders", only: [:new, :create]
  end

  resources :orders, controller: "orders", only: [:index]

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: "logout"
  get "/signup" => "users#new", as: "signup"
  get 'braintree/new'
  post 'braintree/checkout' => "braintree#checkout", as: "braintree_checkout"
  post 'verify_user' => "users#verify", as: "verify_user"
  post 'unverify_user' => "users#unverify", as: "unverify_user"

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :buy_amount, presence: true, numericality: { greater_than: 0}
  validates :sell_amount, presence: true, numericality: { greater_than: 0}
  validate :check_currency_type

  def check_currency_type
  	errors.add(:sell_currency, "can't be the same as buy currency") if buy_currency == sell_currency
  end

  def self.search(term,type)
  	if term && type == "buy"
  		where('buy_currency LIKE ?', "%#{term.upcase}%")
  	elsif term && type == "sell"
  		where('sell_currency LIKE ?', "%#{term.upcase}")
  	else
  		all
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = Order.new
		@user = User.find(params[:user_id])
		@user_balances = @user.balances
	end

	def create
		@order = current_user.orders.new(order_params)
		if @order.save
			balance = current_user.balances.find_by(currency: @order.sell_currency)
			new_balance = balance.amount - @order.sell_amount.to_f
			balance.update(amount: new_balance)
			redirect_to user_path(current_user), :flash => { :success => "Order successfully created!" }
		else
			flash[:error] = "An error has occured"
			render "new"
		end
	end

	def index
		if current_user
			@user = current_user
			@balances = @user.balances
		end

		if params[:term] != "" && params[:term] != nil
			@orders = []
			Order.where(completed: false).where.not(user_id: current_user.id).search(params[:term],"buy").each { |o| @orders << o }
			Order.where(completed: false).where.not(user_id: current_user.id).search(params[:term],"sell").each { |o| @orders << o }
		else
			if current_user
				@orders = Order.all.where(completed: false).where.not(user_id: current_user.id)
			else
				@orders = Order.all.where(completed: false)
			end
		end
	end

	def show
		@order = Order.find(params[:id])
	end

	# def buy_orders
	# 	@orders = Order.where(order_type: 0)
	# end

	# def sell_orders
	# 	@orders = Order.where(order_type: 1)
	# end

	private
	def order_params
		params.require(:order).permit(:buy_currency, :buy_amount, :sell_currency, :sell_amount, :order_type, :term)
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="form-group">
	<%= form.radio_button(:order_type, 0, checked: true) %>
	<%= form.label :buy_order %>
	<%= form.radio_button(:order_type, 1) %>
	<%= form.label :sell_order %>
</div>

<div class="form-group">
	<%= form.label :buy_currency %>
	<select name="order[buy_currency]">
		<option value="MYR">MYR</option>
		<option value="SGD">SGD</option>
		<option value="USD">USD</option>
		<option value="GBP">GBP</option>
		<option value="AUD">AUD</option>
	</select>
</div>

<div class="form-group">
	<%= form.label :buy_amount %>
	<%= form.number_field :buy_amount %>
</div>

	
<div class="form-group">
	<%= form.label :sell_currency %>
	<select name="order[sell_currency]">
		<option value="MYR">MYR - Your balance: <%= @user_balances.find_by(currency: "MYR").amount %></option>
		<option value="SGD">SGD - Your balance: <%= @user_balances.find_by(currency: "SGD").amount %></option>
		<option value="USD">USD - Your balance: <%= @user_balances.find_by(currency: "USD").amount %></option>
		<option value="GBP">GBP - Your balance: <%= @user_balances.find_by(currency: "GBP").amount %></option>
		<option value="AUD">AUD - Your balance: <%= @user_balances.find_by(currency: "AUD").amount %></option>
	</select>
</div>


<div class="form-group">
	<%= form.label :sell_amount %>
	<%= form.number_field :sell_amount %>
</div>

app/views/orders/index.html.erb
<div class="container">
	<h1>Orders</h1>

	<%= form_tag(orders_path, method: :get) do %>
	  <%= text_field_tag :term %>
	  <%= submit_tag 'Search', name: nil %>
  	<% end %>
</div>

<% if current_user != nil %>
<%= render partial: "/users/balance" %>
<% end %>

<div class="container">
	<h2>Buy Orders</h2>
  	<% @orders.each do |order| %>
  	<div>
  	  <%= "#{order.user.username} is buying #{order.buy_amount} #{order.buy_currency} for #{order.sell_amount} #{order.sell_currency}" %> 
  	  <%= link_to "SELL #{order.buy_currency}", { :controller => "transactions", :action => "new", :id => order.id } %>
  	</div>
  	<% end %>
</div>

<div class="container">
	<h2>Sell Orders</h2>
  	<% @orders.each do |order| %>
  	<div>
  	  <%= "#{order.user.username} is selling #{order.sell_amount} #{order.sell_currency} for #{order.buy_amount} #{order.buy_currency}" %> 
  	  <%= link_to "BUY #{order.sell_currency}", { :controller => "transactions", :action => "new", :id => order.id } %>
  	</div>
  	<% end %>
</div>

app/views/orders/new.html.erb
<div class="container">
	<h1>New Order</h1>

	<%= form_for [current_user, @order] do |f| %>
		<%= render partial: '/orders/form', object: f %>
		<%= f.submit "New Order", class: "btn btn-primary" %>
	<% end %>
</div>